name: Build docker

on:
  push:
    branches:
      - "main"

env:
  quay_username: ${{ secrets.CCS_QUAY_CCSPORTAL_BUILDER }}
  quay_password: ${{ secrets.CCS_QUAY_CCSPORTAL_BUILDER_PASSWORD }}

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ env.quay_username }}
          password: ${{ env.quay_password }}

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: quay.io/ccsportal/platform-analytics-frontend:latest # TODO: use a git sha or something for the tag
